### ISSUE TITLE
Inform user when manifest is using unsupported version

### ISSUE THREAD

**Issue by velara3** [jardicc/vscode-uxp-validator#7]
Check if the manifest is version 4 or greater. If the version is less than that then is it possible to mention it is not supported (in the code hinting). Some developers may not know they need to add the `manifestVersion: 5` tag to get support. 

![image](https://github.com/jardicc/vscode-uxp-validator/assets/1084127/1130ce6b-4bd3-4f35-8f4a-869cb9b95afc)

I see version support is mentioned in the vscode plugin page: 

https://marketplace.visualstudio.com/items?itemName=JaroslavBereza.uxpvalidator#out-of-scope

**Comment by jardicc** [comment]
Thanks for feedback! I will look at it. The thing is manifest v3 works only in XD. And XD is in maintanance only mode. So it is not going to be developed. But you should be able to use manifest v4-5 in XD as well.

**Comment by jardicc** [comment]
So I updated manifestVersion detection and now it won't fall back to v4 or v5 when version not found or is not supported. It will let you know instead.

![image](https://github.com/jardicc/vscode-uxp-validator/assets/13526959/112c055f-041c-4d8c-8d4a-feaf95a6758f)
![image](https://github.com/jardicc/vscode-uxp-validator/assets/13526959/22507ba6-4b85-46b4-b334-ccfc3ba4658a)
![image](https://github.com/jardicc/vscode-uxp-validator/assets/13526959/ac65fb3d-29ea-4055-be89-2a33dc9bebbe)
